### PR TITLE
[Enhancement] [Bugfix] Grab Git History Automatically

### LINKED ISSUE #16: [Bug] Crash Due to Missing LOC Diff
It seems as if `commit-analyzer` tends to crash if no LOC diff is present in the input file.

Now, that the verbose output needs to be opted-in explicitly, I found out that line 121 always seems to cause a `CommitParseError::CommitMissing` when there is no LOC diff.

I did not trace down the bug completely, yet, but I assume that perhaps the LOC diff might be considered present, by default.

### PR DESCRIPTION
**Pull request by kevinmatthes**
This patch introduces the automatic reading from Git itself.  It thereby fixes #16 and replaces the feature request from #3.

### CODE REVIEW

File: src/main.rs [hunk 1]
```diff
@@ -1,4 +1,4 @@
-use std::{collections::HashMap, error::Error, fs, io::Write, num::ParseIntError, ops::AddAssign};
```
Comment (kevinmatthes) [inline src/main.rs:1]: `fs` is now used only once, so I removed it from the import list.

File: src/main.rs [hunk 2]
```diff
@@ -84,7 +84,7 @@ fn main() -> Result<(), Box<dyn Error>> {
             return Err(err.into());
         }
     };
-    if matches.opt_present("help") || matches.free.len() < 2 {
```
Comment (kevinmatthes) [inline src/main.rs:87]: The input file became obsolete.

File: src/main.rs [hunk 3]
```diff
@@ -98,8 +98,12 @@ fn main() -> Result<(), Box<dyn Error>> {
...
     };
     let path = matches.opt_str("output");
-    let commits_path = &matches.free[1];
-    let commits = fs::read_to_string(commits_path).unwrap();
+    let commits = std::process::Command::new("git")
+        .arg("log")
+        .arg("--numstat")
+        .output()
+        .expect("This is not a Git repository");
+    let commits = String::from_utf8(commits.stdout).unwrap();
```
Comment (kevinmatthes) [inline src/main.rs:106]: Now, `git log --numstat` is called *from the application itself*.  This not only fixes #16 due to always ensuring the correct format but also replaces the reading from `stdin`, see #3, since one obviously does not need to do anything to get the history extracted.

File: src/main.rs [hunk 4]
```diff
@@ -160,7 +164,7 @@ fn main() -> Result<(), Box<dyn Error>> {
     println!("Found {} commits overall", commit_count);
 
     if let Some(path) = path {
-        let mut file = fs::File::create(path)?;
+        let mut file = std::fs::File::create(path)?;
```
Comment (kevinmatthes) [inline src/main.rs:167]: See the first comment.

File: src/main.rs [hunk 5]
```diff
@@ -183,8 +187,8 @@ fn main() -> Result<(), Box<dyn Error>> {
 /// introduction to the meaning of the configured `options`, to `stdout`.
 fn usage(options: &getopts::Options) {
     println!(
-        "Parses the output of `git log`.\n\n{}",
-        options.usage("Usage: commit-analyzer <FILE> [OPTIONS]")
+        "Parses the Git history.\n\n{}",
+        options.usage("Usage: commit-analyzer [OPTIONS]")
```
Comment (kevinmatthes) [inline src/main.rs:191]: The in-app docs needed to be adjusted.  Suggestions for better wordings are welcome.  :wrench:

File: README.md [hunk 6]
```diff
@@ -2,24 +2,22 @@
```
Comment (kevinmatthes) [inline README.md:2]: The README explanation needed to be updated, as well.  I took the chance to also enhance the wording, if possible.

Any wishes for further changes?  :wrench:

**Review by kevinmatthes — COMMENTED** [review]
I added some initial explanation the most important points.

File: src/main.rs (hunk 2 above)
Comment (wert007) [reply src/main.rs:87]: I think input files should always be an option to the user. If they call the program without any parameters (and maybe a flag, so that the help will still be display by default), the program will parse `stdin`, and otherwise if a file (or maybe multiple, but that is another topic..) is supplied, it will just parse that.

File: src/main.rs (hunk 5 above)
Comment (wert007) [reply src/main.rs:191]: Hmm, why though? Maybe we need to be more precise, how that output can be supplied, but at its core this is still true.

**Review by wert007 — CHANGES_REQUESTED** [review]
Great to see your first take at an actual new feature to the tool. Added some comments 😄

File: src/main.rs (hunk 3 above)
[the remark this answers is not in the document]
Comment (kevinmatthes) [reply src/main.rs:106]: Okay, I am going to change the `expect` and `unwrap` to the suggested `?`.  Their usage originates from the examples in the official documentation.

[the remark this answers is not in the document]
Comment (kevinmatthes) [reply src/main.rs:106]: If you say "input as an option," how about making it literally an option?  Just like `-o`?

**Comment by wert007** [comment]
While this is true, I would prefer if you tried to improve your commit sizes. It makes reviewing easier, especially, if you do it on per commit basis, and it would also be nice to simply merge the commits in to the main branch, to have a better overview over the commits. Ironically, tools like this, would profit from this. 😄

File: README.md (hunk 6 above)
Comment (wert007) [reply README.md:2]: I think it looks good! 👍

File: src/main.rs (hunk 3 above)
Comment (kevinmatthes) [reply src/main.rs]: Shall I make it literally an option?

File: src/main.rs (hunk 5 above)
Comment (kevinmatthes) [reply src/main.rs:190]: "Grabs and parses the output of `git log --numstat`." :wrench: :question:

File: src/main.rs (hunk 3 above)
[the remark this answers is not in the document]
Comment (wert007) [reply src/main.rs]: > Okay, I am going to change the `expect` and `unwrap` to the suggested `?`. Their usage originates from the examples in the official documentation.

Yeah, especially in the beginning they are very helpful, to sketch out programs, without having to think about every possible error. My other rust programs also have a few (or maybe even a lot.. 😅 ) of them. But since this is rather small, and easily checked, something like the `?` operator is preferable. (Even though I'm not too sure, how I feel about it. Its output to the console is not the nicest imho)

> If you say "input as an option," how about making it literally an option? Just like `-o`?

Yes, I would be down for it. 😄

Comment (wert007) [reply src/main.rs]: I think you replied to the wrong comment here? This against letting the program call `git log --numstat` itself, in favor for stdin reading/parsing.

File: src/main.rs (hunk 2 above)
Comment (kevinmatthes) [reply src/main.rs:87]: Suggestion for the behaviour:

1. If `--git` is specified, grab from the local Git history.
2. If `-i` is specified, read from the given file.
3. If none of the above is specified, read from `stdin`.

Comment (wert007) [reply src/main.rs:87]: Generally, yeah, I would like that. Just one thing:

If one does not know the program, and just runs it without any parameters, it will do nothing, since it is waiting for user input, and the user does not know, what they have to do. Maybe, that is fine and the user will think of using `--help` but idk.. 😅

File: src/main.rs (hunk 5 above)
Comment (wert007) [reply src/main.rs:190]: I am actually not sure, If the in-app docs need to be adjusted. I just tried it and ended up with the original text.. 😅 

The problem with yours is, that is only true if something like `--git` would be supplied.

File: src/main.rs (hunk 2 above)
Comment (kevinmatthes) [reply src/main.rs:87]: :wrench: :heavy_check_mark:

File: src/main.rs (hunk 3 above)
Comment (kevinmatthes) [reply src/main.rs]: :wrench: :heavy_check_mark:

[the remark this answers is not in the document]
Comment (kevinmatthes) [reply src/main.rs]: :wrench: :heavy_check_mark:

File: src/main.rs (hunk 5 above)
Comment (kevinmatthes) [reply src/main.rs:200]: :wrench: :heavy_check_mark:

**Comment by kevinmatthes** [comment]
Users now need to specify a source to read from.  This might be either the local Git history (`--git`) or an input file (`-i`).  `stdin` will be added later, perhaps with an option, as well, such that a call without options will redirect to the help overview.

File: README.md [hunk 7]
```diff
@@ -38,8 +36,10 @@ main directory of this repository.
 | `--email-contains`        | `-e`  | (**OR**) Filter for certain author emails.                                |
 | `--email-equals`          |       | (**OR**) Filter for certain author emails.                                |
 | `--duration`              | `-d`  | The time which may pass between two commits that still counts as working. |
-| `--file-extension`        | `-f`  | (**OR**) Filter loc for certain file extension, e.g.`-f cpp`.             |
+| `--file-extension`        | `-f`  | (**OR**) Filter loc for certain file extension, e.g. `-f cpp`.            |
+| `--git`                   |       | Grab the input data from the local Git history.                           |
```
Comment (wert007) [inline README.md:40]: "Grab the input data from the local git repository."

Maybe? Maybe also "Git" instead of "git", it just looks very unusual.. 😅

File: src/main.rs [hunk 8]
```diff
@@ -1,10 +1,11 @@
-use std::{collections::HashMap, error::Error, fs, io::Write, num::ParseIntError, ops::AddAssign};
+use std::{collections::HashMap, error::Error, io::Write, num::ParseIntError, ops::AddAssign};
 
 fn main() -> Result<(), Box<dyn Error>> {
     let mut opts = getopts::Options::new();
     let opts = opts
-        .optflag("v", "verbose", "Always show the entire output.")
+        .optflag("", "git", "Grab the input data from the local Git history.")
```
Comment (wert007) [inline src/main.rs:6]: Same as above.

File: src/main.rs [hunk 9]
```diff
@@ -98,8 +101,18 @@ fn main() -> Result<(), Box<dyn Error>> {
...
+        let process = std::process::Command::new("git")
+            .arg("log")
+            .arg("--numstat")
+            .output()?;
+        String::from_utf8(process.stdout)?
+    } else if matches.opt_present("input") {
+        let path = matches.opt_str("input").unwrap();
+        std::fs::read_to_string(path)?
+    } else {
+        String::new()
```
Comment (wert007) [inline src/main.rs:114]: Hmm, while this actually runs fine, maybe something like
```rust
todo!("Reading git log from stdin")
```
or `unimplemented!`.

While this would exit the program, it would also make clear, both to the user, and the programmer, that here is something missing. And since this is only temporary, it should be fine imo.

File: src/main.rs (hunk 5 above)
Comment (wert007) [reply src/main.rs:200]: Did you mean to change this?

Comment (kevinmatthes) [reply src/main.rs:200]: Yes, I meant to change it.  And I already changed it:  you now always an option to specify the input.  So the synopsis part is correct.

File: README.md (hunk 7 above)
Comment (kevinmatthes) [reply README.md:40]: I neither understand the purpose of "maybe" in your comment nor the requested change.  It already is "Git" instead of "git" because the latter one is too unusual since Git has the same status as GCC has:  both are a standard.

I implemented the lower case spelling as option trigger anyway since options are usually given as lower case words or phrases.

File: src/main.rs (hunk 8 above)
Comment (kevinmatthes) [reply src/main.rs:6]: Same as above, too.  I do not get what you intend to express.

File: src/main.rs (hunk 5 above)
Comment (kevinmatthes) [reply src/main.rs:200]: The sole open point might be that the description should receive a change.  If so, please provide a suggestion. :wrench:

File: src/main.rs (hunk 9 above)
Comment (kevinmatthes) [reply src/main.rs]: :wrench: :heavy_check_mark:

File: src/main.rs (hunk 5 above)
Comment (wert007) [reply src/main.rs:200]: I think "Parses the Git history" is quite colloquial and maybe not even correct. I have never heard git commits being called the git history. If you have something, that does call it that, I'd be interested. 😄

File: README.md (hunk 7 above)
Comment (wert007) [reply README.md:42]: Yeah, sorry. I was rambling a bit.

The text in quotes was a proposal. And then I debated a bit about the Git capitalization, but you are right.

I proposed the change for the same reason, as I said in another comment:

> I think "Parses the Git history" is quite colloquial and maybe not even correct. I have never heard git commits being called the git history. If you have something, that does call it that, I'd be interested. 😄

So, if you find an example there, it would also resolve this.

File: src/main.rs (hunk 8 above)
Comment (wert007) [reply src/main.rs:6]: Hope this cleared up with my other comments. 

Also:
> I think "Parses the Git history" is quite colloquial and maybe not even correct. I have never heard git commits being called the git history. If you have something, that does call it that, I'd be interested. 😄

So, if you find an example there, it would also resolve this.

File: README.md (hunk 7 above)
Comment (kevinmatthes) [reply README.md:42]: The official Git introduction by Scott Chacon and Ben Straub calls the set of previous commits the "Git history".  There are chapters about "Rewriting the History" in the book, for instance, so I oriented on it when suggesting the new wording.

File: src/main.rs (hunk 8 above)
Comment (kevinmatthes) [reply src/main.rs:6]: See above.

File: README.md (hunk 7 above)
Comment (kevinmatthes) [reply README.md:42]: The book is named "Pro Git", published by Apress.  The latest printed version should be the 2nd edition.

Comment (wert007) [reply README.md:42]: Great. Then I'll merge this request. 😄
